Vagrant.configure("2") do |config|
  config.vm.box = "centos/7"
  config.vm.network "public_network", type: "dhcp"
  config.vm.provision "shell", inline: "yum install ansible"
end

config.vm.provider "virtualbox" do |v|
v.memory = 4024
v.cpus = 4
v.name = "Asembli Control"
end
