$ansible = <<-SCRIPT
yum install epel-release -y
yum install ansible -y
SCRIPT

Vagrant.configure("2") do |config|
  config.vm.box = "centos/7"
  config.vm.network "public_network", type: "dhcp"
  config.vm.provision "shell", inline: $ansible

  config.vm.provider "virtualbox" do |v|
  v.memory = 4024
  v.cpus = 4
  v.name = "Asembli Control"

end
end
