---
- hosts: all
  tasks:
    - name: 'Instala PHP5'
      apt:
        name: php5
        state: latest
      become: yes
    - name: 'Istala o Apache2'
      apt:
        name: apache2
        state: latest
      become: yes
    - name: 'Istala o modphp'
      apt:
        name: libapache2-mod-php5
        state: latest
      become: yes
