Vagrant.configure("2") do |config|
  config.vm.box = "generic/oracle8"
  config.vm.network "forwarded_port", guest: 80, host:8080
  config.vm.network "public_network", type: "dhcp"
  config.vm.provision "shell", inline: " dnf install -y oracle-database-preinstall-19c
"
config.vm.provider "virtualbox" do |v|
v.memory = 4024
v.cpus = 2
v.name = "Oracle"

end
end
