Vagrant.configure("2") do |config|
  config.vm.box = "StefanScherer/windows_2019"
  config.vm.network "public_network", type: "dhcp"

  config.vm.provider :virtualbox do |vb|
    vb.gui = true
  end
end
